### ISSUE TITLE
Sensor not loading

### ISSUE THREAD

**Issue by Xornop** [NemesisRE/sensor.plex_recently_added#3]
**Describe the Bug**
sensor.plex_recently_added doesn't load correctly.

**The Error**
plex_recently_added: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/config/custom_components/plex_recently_added/sensor.py", line 269, in async_update
    sub_sec = json.loads(sub_sec)
  File "/usr/local/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Indicate if you followed all steps in the [troubleshooting doc](https://github.com/NemesisRE/upcoming-media-card/blob/master/troubleshooting.md)**
I believe so.

**What data does the sensor display if any?**
none

**What displays when visiting the API URL from the troubleshooting guide?**
Data about my most recently added videos.

**Does the default Home Assistant Plex component work for you?**
Yes

**Home Assistant Version**
2022.10.5

**Additional Context**
custom:plex-meets-homeassistant works fine with the same ip, port and token, so i am sure that i have entered those correctly

**Comment by WeiYang1982** [comment]
The same to me

**Comment by B4dC4rd** [comment]
Same for me: 

plex_recently_added: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
    await task
  File "/config/custom_components/plex_recently_added/sensor.py", line 269, in async_update
    sub_sec = json.loads(sub_sec)
  File "/usr/local/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by DulinDuskhawk** [comment]
Yep samen here. 
Seems like this problem occured spontaneously since HA 2024.10.x

**Comment by mkanet** [comment]
@B4dC4rd @DulinDuskhawk  this repo hasnt been updated in years.  

You would need to use the [original/official version](https://github.com/custom-components/sensor.plex_recently_added) of this integration which is updated regularly.  Lots of new features and enhancements!  This integration can now be installed via the Home Assistant GUI with lots of new settings/options/bugfixes.  

**In fact, all the official/original sibling integrations and the original Upcoming Media Card itself are updated regularly.**  For any feature requests or bugfixes, you would have to submit an issue to the correct repos below.

**Official Plex Recently Added:**
https://github.com/custom-components/sensor.plex_recently_added

**Official Upcoming Media Card:**
https://github.com/custom-cards/upcoming-media-card

**Official Sonarr Upcoming Media Integration:**
https://github.com/custom-components/sensor.sonarr_upcoming_media

**Official Radarr Upcoming Media Integration:**
https://github.com/custom-components/sensor.radarr_upcoming_media

**Note:** that all these original repos are in the process of being added back to HACS VERY soon!  In the meantime, you would have to [temporarily add the repo to Home Assistant](https://www.hacs.xyz/docs/faq/custom_repositories/) in order to install the integration from HACS.  You will also see a temporary message about the integration being previously archived.  You can ignore than message until the repo(s) are back on HACS.
